### ISSUE TITLE
Camera Image Saving

### ISSUE THREAD

**Issue by akeditzz** [esafirm/android-image-picker#145] opened 2018-06-11 11:32 UTC
When click image from camera it save two different images in two locations. please help

**Comment by esafirm** [comment] 2018-06-17 10:01
@akeditzz can you elaborate more? Maybe some sample code?

**Comment by Virtuozoff** [comment] 2018-06-18 08:47
@esafirm 
I can. I have the same issue. It happens after making photo by camera. Picker saves it to 2 different folders. I don't know why and how to fix it.
![screenshot](https://user-images.githubusercontent.com/9018771/41526548-3cb7a2b0-72ed-11e8-9b04-5625bb27e90b.png)

**Comment by esafirm** [comment] 2018-07-21 15:08
@Virtuozoff well this is strange. Can you reproduce this with the sample app? Thank you

**Comment by esisa** [comment] 2018-10-24 08:10
Same thing happens for me.

**Comment by esafirm** [comment] 2021-06-20 02:40
Closing this because it's too old. Please feel free to reopen if this is happening again in 3.x

**Closed by esafirm** 2021-06-20 02:40 UTC
