### ISSUE TITLE
NoSuchFieldError

### ISSUE THREAD

**Issue by amalive** [esafirm/android-image-picker#6] opened 2016-11-11 08:32 UTC
FATAL EXCEPTION: main
                                                                        java.lang.NoSuchFieldError: com.esafirm.imagepicker.R$id.menu_camera
                                                                            at com.esafirm.imagepicker.features.ImagePickerActivity.onPrepareOptionsMenu(ImagePickerActivity.java:201)
                                                                            at android.app.Activity.onPreparePanel(Activity.java:2600)
                                                                            at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:532)
                                                                            at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:521)
                                                                            at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
                                                                            at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:358)
                                                                            at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
                                                                            at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:567)
                                                                            at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
                                                                            at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
                                                                            at android.os.Handler.handleCallback(Handler.java:808)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                            at android.os.Looper.loop(Looper.java:193)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5388)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655)
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by esafirm** [comment] 2016-11-11 10:49
What version of Android and `ImagePicker` do you use to produce this issue? 
What phone do you use?

Is it always reproducible?

**Comment by amalive** [comment] 2016-11-11 13:34
I'm testing on Honor 6 (Android 6.0) & Lenovo S650 (Android version 4.4.2). 
ImagePicker 1.2.2.


Always get the same error.

**Comment by amalive** [comment] 2016-11-11 13:39
I suspect it clash with my appcompat. Because when I download your source code & run,  it working well. But when I try in my current project, it getting error.

**Comment by esafirm** [comment] 2016-11-12 00:42
Thanks for the report, will look deeper into that later.

Since you're the one with reproducible device, why not contribute? 😄 
Contributors are very welcomed. 😊

**Comment by pdavid0** [comment] 2016-11-14 19:32
Same Error on a Nexus 6P and Android 7.1

I don't think it has to do with the device. There's something wrong in your lib.

I will try to debug it and sent a PR.

**Comment by esafirm** [comment] 2016-11-15 01:28
@pdavid0 I know, but in is not reproducible in my devices (typical reason to QA) 

Will also look into it.

**Comment by LadwaAditya** [comment] 2016-11-15 08:50
java.lang.RuntimeException: Unable to start activity ComponentInfo{sg.com.fuzzie.debug/com.esafirm.imagepicker.features.ImagePickerActivity}: java.lang.ClassCastException: android.support.design.widget.AppBarLayout cannot be cast to android.support.v7.widget.Toolbar

**Comment by pdavid0** [comment] 2016-11-15 16:16
@esafirm You don't have the bug because you are not testing with the same app. The Error come from duplicates in file names.

Your lib is declaring a menu file "menu_main.xml" and so is my app. This creates confusion in the resulting static R class.

**Comment by esafirm** [comment] 2016-11-15 17:58
@pdavid0 Hi, thanks for creating a PR for it.
I'm trying to reproduce it on the sample, unfortunately it's not happening.

Is it have to be a different app or is this some Support Library Bug?

AFAIK static R class is separated by package name so there's should be no confusion

**Comment by pdavid0** [comment] 2016-11-15 18:22
@esafirm http://stackoverflow.com/questions/36179847/no-static-field-list-container-of-type-i-in-class-landroid-support-v7-preference

**Comment by esafirm** [comment] 2016-11-15 18:25
@pdavid0 @LadwaAditya 

> java.lang.RuntimeException: Unable to start activity ComponentInfo{sg.com.fuzzie.debug/com.esafirm.imagepicker.features.ImagePickerActivity}: java.lang.ClassCastException: android.support.design.widget.AppBarLayout cannot be cast to android.support.v7.widget.Toolbar

Maybe this one is caused by the duplicate naming issue too. 

please try this snapshot @LadwaAditya 
`com.github.esafirm.android-image-picker:imagepicker:-SNAPSHOT`

**Comment by esafirm** [comment] 2016-11-15 18:30
@pdavid0 Just wondering what the root cause is and why it's not reproducible in the sample.

Please try the snapshot. If it's good i'm gonna close this one and release `1.2.3`
`com.github.esafirm.android-image-picker:imagepicker:-SNAPSHOT`

**Comment by pdavid0** [comment] 2016-11-15 19:12
Error:Failed to resolve: com.github.esafirm.android-image-picker:imagepicker:-SNAPSHOT

**Comment by pdavid0** [comment] 2016-11-15 19:16
I was able to reproduce the bug.

Simply add a file called : `res/menu/image_picker_menu_main.xml` to the sample project.

```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
  <item
      android:icon="@color/black"
      android:id="@+id/menu_test"
      >
  </item>
</menu>
```

```
11-15 14:15:22.309 8698-8698/com.esafirm.imagepicker.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.esafirm.imagepicker.sample, PID: 8698
                                                                              java.lang.NoSuchFieldError: No field menu_camera of type I in class Lcom/esafirm/imagepicker/R$id; or its superclasses (declaration of 'com.esafirm.imagepicker.R$id' appears in /data/data/com.esafirm.imagepicker.sample/files/instant-run/dex/slice-slice_6-classes.dex)
                                                                                  at com.esafirm.imagepicker.features.ImagePickerActivity.onPrepareOptionsMenu
```

**Comment by esafirm** [comment] 2016-11-16 00:17
> Failed to resolve: com.github.esafirm.android-image-picker:imagepicker:-SNAPSHOT

What? 

http://www.methodscount.com/?lib=com.github.esafirm.android-image-picker%3Aimagepicker%3A-SNAPSHOT

Did you already add this? 

```groovy
allprojects {
		repositories {
			maven { url "https://jitpack.io" }
		}
	}
```

---

I believe this is not a mere duplication in naming issues, yes, there are others on the SO whom dealing with the same thing. But i just can't reproduce this both in the sample and our internal product that using this library.

Anyway, i will just release the `1.2.3` later this day. Will close this for now. Thanks for your support.

**Closed by esafirm** 2016-11-16 00:17 UTC
Labels: bug, help wanted
