### ISSUE TITLE
Bug: Camera pictures are not accessible when storage permission has not been given.

### ISSUE THREAD

**Issue by kavitamp** [esafirm/android-image-picker#412] opened 2022-10-18 15:29 UTC
## Expected Behavior
Let the user proceed further with the captured image even when storage permission is denied

## Actual Behavior
Camera pictures are not accessible when storage permission has not been given.

## Steps to Reproduce the Problem
Let the user use the camera when storage permission has not been given. Currently, the app lets users open the camera but doesn't let them proceed as storage permission is denied.
Steps:
1. Open image picker functionality
2. Deny storage permission
3. Click on the camera icon
4. Capture the image and proceed further
5. Nothing happens after that

### Issue recording:
https://user-images.githubusercontent.com/20037228/196465424-49d6e17e-c267-4721-af81-baeed1856127.mp4

## Specifications

  - Image Picker Version:
  - Android OS: Android 13
  - Phone: OnePlus

**Comment by kavitamp** [comment] 2022-10-18 15:30
@esafirm I have fixed the issue in this PR(https://github.com/esafirm/android-image-picker/pull/409), please take a look.
Thanks!

**Comment by esafirm** [comment] 2022-11-19 22:48
Thanks for the PR and issue. The solution should be not adding a workaround for this.

Anyway, this is a duplicate of https://github.com/esafirm/android-image-picker/issues/422

Closing this

**Closed by esafirm** 2022-11-19 22:48 UTC
