### ISSUE TITLE
crash on Samsung s10 - when opening gallery with video - related to getVideoDurationLabel

### ISSUE THREAD

**Issue by shay127** [esafirm/android-image-picker#323] opened 2020-12-29 18:24 UTC
D/AndroidRuntime(25890): Shutting down VM
E/AndroidRuntime(25890): FATAL EXCEPTION: main
E/AndroidRuntime(25890): Process: com.twtech.twelveqa, PID: 25890
E/AndroidRuntime(25890): java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
E/AndroidRuntime(25890):        at android.media.MediaMetadataRetriever.setDataSource(Native Method)
E/AndroidRuntime(25890):        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:82)
E/AndroidRuntime(25890):        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:173)
E/AndroidRuntime(25890):        at com.esafirm.imagepicker.helper.ImagePickerUtils.getVideoDurationLabel(ImagePickerUtils.java:114)
E/AndroidRuntime(25890):        at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.kt:67)
E/AndroidRuntime(25890):        at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.kt:23)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
E/AndroidRuntime(25890):        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
E/AndroidRuntime(25890):        at android.view.View.layout(View.java:23750)
E/AndroidRuntime(25890):        at android.view.ViewGroup.layout(ViewGroup.java:7277)
E/AndroidRuntime(25890):        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
E/AndroidRuntime(25890):        at android.view.View.layout(View.java:23750)
E/AndroidRuntime(25890):        at android.view.ViewGroup.layout(ViewGroup.java:7277)
E/AndroidRuntime(25890):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime(25890):        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime(25890):        at android.view.View.layout(View.java:23750)
E/AndroidRuntime(25890):        at android.view.ViewGroup.layout(ViewGroup.java:7277)
E/AndroidRuntime(25890):        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
E/AndroidRuntime(25890):        at android.view.View.layout(View.java:23750)
E/AndroidRuntime(25890):        at android.view.ViewGroup.layout(ViewGroup.java:7277)
E/AndroidRuntime(25890):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime(25890):        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime(25890):        at android.view.View.layout(View.java:23750)
E/AndroidRuntime(25890):        at android.view.ViewGroup.layout(ViewGroup.java:7277)
E/AndroidRuntime(25890):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime(25890):        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime(25890):        at android.view.View.layout(View.java:23750)
E/AndroidRuntime(25890):        at android.view.ViewGroup.layout(ViewGroup.java:7277)
E/AndroidRuntime(25890):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime(25890):        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime(25890):        at android.view.View.layout(View.java:23750)
E/AndroidRuntime(25890):        at android.view.ViewGroup.layout(ViewGroup.java:7277)
E/AndroidRuntime(25890):        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
E/AndroidRuntime(25890):        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
E/AndroidRuntime(25890):        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
E/AndroidRuntime(25890):        at android.view.View.layout(View.java:23750)
E/AndroidRuntime(25890):        at android.view.ViewGroup.layout(ViewGroup.java:7277)
E/AndroidRuntime(25890):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime(25890):        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime(25890):        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1099)
E/AndroidRuntime(25890):        at android.view.View.layout(View.java:23750)
E/AndroidRuntime(25890):        at android.view.ViewGroup.layout(ViewGroup.java:7277)
E/AndroidRuntime(25890):        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3712)
E/AndroidRuntime(25890):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3164)
E/AndroidRuntime(25890):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
E/AndroidRuntime(25890):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
E/AndroidRuntime(25890):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
E/AndroidRuntime(25890):        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
E/AndroidRuntime(25890):        at android.view.Choreographer.doFrame(Choreographer.java:732)
E/AndroidRuntime(25890):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
E/AndroidRuntime(25890):        at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(25890):        at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(25890):        at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(25890):        at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime(25890):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25890):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(25890):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

  - Image Picker Version: 2.4.1
  - Phone: Samsung s10

**Comment by shay127** [comment] 2020-12-29 21:59
https://stackoverflow.com/questions/46029813/mediametadataretriever-setdatasourcenative-method-causes-runtimeexception-sta

maybe this can help

**Comment by wiwuwa** [comment] 2021-02-18 08:06
https://github.com/esafirm/android-image-picker/pull/331#issue-575480123

I met the same problem and fork a branch to fix this problem.
This problem is caused by targeting to compile version 29, app is not permitted to access the file through absolute path of the file. I solve this by using content uri to access the file.

**Comment by esafirm** [comment] 2021-03-18 03:05
This should be fixed on `2.4.5` (thanks @wiwuwa for the PR)
If the problem still exist, please don't hesitate to comment on this again. 

Alternatively, you can always create your own `ImageFileLoader` and set it with

```
ImagePickerComponentsHolder.setInternalComponent
```

I'm closing this issue for now

**Closed by esafirm** 2021-03-18 03:05 UTC

**Comment by Valgaal** [comment] 2021-04-06 11:49
Crash still exists in 2.4.5 on Xiaomi Redmi Note 8 Pro
Fatal Exception: java.lang.IllegalArgumentException
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:173)
       at com.esafirm.imagepicker.helper.ImagePickerUtils.getVideoDurationLabel(ImagePickerUtils.java:114)
       at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.kt:70)
       at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.kt:25)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
       at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
