### ISSUE TITLE
Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found

### ISSUE THREAD

**Issue by jinfagang** [esafirm/android-image-picker#107] opened 2018-01-31 11:50 UTC
Hi, thanks for this very good library, really saved my life when app needs picking multiple images. However, currently I get a only one problem which specific on Xiaomi android devices:

```
Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
```

Totally have no idea why this error happen, and other device just ok. I know it's Xiaomi's problem, but I am in China and this device are so many, how to solve this anyway?

**Comment by esafirm** [comment] 2018-02-01 03:23
Does the app crash or something? 
When exactly this error happen? 
Can you attach the full stack trace?

**Comment by jinfagang** [comment] 2018-02-01 08:55
@esafirm Hi, no crash, seem the exception were be catched. The only trace back can be seem from logcat. Just `Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found`. And can not open image pickcer. This error only shows on Xiaomi devices.

**Comment by esafirm** [comment] 2018-02-12 01:51
It seems like the issue is not from the image picker itself. On [this](https://github.com/BlinkID/blinkid-android/issues/42) it mentioned the issue is from the audio processor or something. 

I have Xiaomi Note 4 myself, unfortunately the issue didn't reproducible as well.

**Comment by jinfagang** [comment] 2018-02-12 14:36
Hi, esa, thanks for replying the related issue, I am using Redmi 5 Plus. If you find solution about this pls let me know!

**Comment by esafirm** [comment] 2018-02-14 18:26
@jinfagang will do! As for now, i will closing this issue. Please don't hesitate to reopen.

**Closed by esafirm** 2018-02-14 18:26 UTC

**Comment by unicornRainbows** [comment] 2018-07-03 14:49
FML

**Comment by cloewen8** [comment] 2018-08-13 22:49
Just had this issue with Android Nexus 6 (API 25) virtual device.

**Comment by shekharartemedia** [comment] 2018-11-17 06:17
Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found. i am getting this issue  on lava phone when i open the gallery from my app.

**Comment by Rameez-Rahil** [comment] 2019-12-06 12:43
Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found.in my emmulator pixel 2XL device

**Comment by EmreOzkose** [comment] 2020-01-01 15:02
E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found in my virtual device : Nexus 5 API 24
