### ISSUE TITLE
 Cannot bind argument at index 1 because the index is out of range.  The statement has 0 parameters

### ISSUE THREAD

**Issue by tasjapr** [esafirm/android-image-picker#395] opened 2021-11-22 19:02 UTC
## Expected Behavior
capture photo with the next code works fine:

```
imagePickerLauncher = registerImagePicker {
            if (it.firstOrNull() != null) {
                doneBtn?.setTextColor(ContextCompat.getColor(context ?: return@registerImagePicker, R.color.black))
                user?.selectedImage = it.firstOrNull()?.uri
                user?.localImage = it.firstOrNull()?.path
            }

            Glide.with(activity ?: return@registerImagePicker)
                .load(user?.selectedImage ?: user?.localImage)
                .listener(object : RequestListener<Drawable> {
                    override fun onLoadFailed(e: GlideException?, model: Any?, target: Target<Drawable>?, isFirstResource: Boolean): Boolean {
                        e?.printStackTrace()
                        return false
                    }

                    override fun onResourceReady(resource: Drawable?, model: Any?, target: Target<Drawable>?, dataSource: DataSource?, isFirstResource: Boolean): Boolean {
                        return false
                    }
                })
                .apply(RequestOptions.circleCropTransform())
                .into(userImageIv)
        }

imagePickerLauncher?.launch(CameraOnlyConfig())

```

but when I try to select image from Galerry app crashes with next stacktrace:

```
E/AndroidRuntime: FATAL EXCEPTION: pool-27-thread-1
    Process: my_app, PID: 11648
    java.lang.IllegalArgumentException: Cannot bind argument at index 1 because the index is out of range.  The statement has 0 parameters.
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
        at android.content.ContentResolver.query(ContentResolver.java:1183)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.queryData(DefaultImageFileLoader.kt:118)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.queryData$default(DefaultImageFileLoader.kt:83)
        at com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.run(DefaultImageFileLoader.kt:206)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

## Steps to Reproduce the Problem
Run the following code:

```
 imagePickerConfig = ImagePickerConfig {
            isShowCamera = false
            mode = ImagePickerMode.SINGLE
            theme = R.style.ImagePickerTheme
            arrowColor = ContextCompat.getColor(context ?: return@ImagePickerConfig, R.color.redesign_main_black)
            savePath = ImagePickerSavePath((context as Context).getExternalFilesDir(null)?.path ?: return@ImagePickerConfig)
        }

imagePickerConfig?.let { imagePickerLauncher?.launch(it) }
```

## Specifications

  - Image Picker Version: 3.0.0-beta4
  - Android OS: 11
  - Phone: Pixel 2, Xiaomi Redmi Note 10 Pro

**Comment by tasjapr** [comment] 2021-11-23 10:28
I checked this also on other versions of the library with the same devices, `imagePickerConfig` and `imagePickerLauncher`: 

- 3.0.0-beta1 - works well
- 3.0.0-beta2 - not working
- 3.0.0-beta3 - not working
- 3.0.0-beta4 - not working

**Comment by esafirm** [comment] 2022-04-24 04:40
Duplicate of https://github.com/esafirm/android-image-picker/issues/381

**Closed by esafirm** 2022-04-24 04:40 UTC
