### ISSUE TITLE
Cancelled camera shots leave 0B artifacts

### ISSUE THREAD

**Issue by rustycamper** [esafirm/android-image-picker#188] opened 2019-01-03 21:48 UTC
When user takes a pic using the camera and then cancels (X outs) the image, an empty 0 byte file is left on the file system.

**Comment by esafirm** [comment] 2019-02-26 04:35
Yeah, but sometimes i can't reproduce it. Do you think this is the camera app bug? 
I'm very happy to review the PR for this

**Comment by kroegerama** [comment] 2019-04-05 08:00
Until @esafirm accepts this pull request and creates a new release, everyone can use:
`implementation 'com.kroegerama:android-image-picker:4583344'`
So the device will not get filled up with empty files.

**Comment by esafirm** [comment] 2019-07-15 16:52
Hi sorry been busy for the past few months. The fix is already merged. Cheers!

**Closed** 2019-07-15 16:51 UTC
Labels: bug, help wanted
