### ISSUE TITLE
Camera Captured Image is not showing in gallary in Oreo

### ISSUE THREAD

**Issue by taskfriendinc** [esafirm/android-image-picker#86] opened 2017-12-08 09:20 UTC
Hello,

Downloaded code and run in Oreo device, observed that if you capture images from camera then it is not showing in gallery, only if device OS is Oreo. Which is working fine in Nougat and Marshmallow devices.

Any suggestion???

**Comment by esafirm** [comment] 2017-12-08 14:52
@taskfriendinc hi, this is already reported in here https://github.com/esafirm/android-image-picker/issues/85

Will check on it on the weekend and closing this issue.

**Comment by taskfriendinc** [comment] 2017-12-12 05:09
Any Updates?

**Comment by esafirm** [comment] 2017-12-12 05:32
@taskfriendinc can reproduce it on emulator. I don't have any Oreo device at the moment. Maybe you could do some debugging and report what causing this problem? 😄 

Also, please try https://github.com/esafirm/android-image-picker/releases/tag/1.9.1 
Basically nothing changes besides the tooling sdks version.

**Comment by esafirm** [comment] 2017-12-12 05:34
My speculation is that the `MediaScanner` is not working properly. But then again, it just my guess

**Comment by taskfriendinc** [comment] 2017-12-12 09:07
Error is : 

Caught a RuntimeException from the binder stub implementation.
                                                            android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7286)
                                                                at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:3426)
                                                                at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
                                                                at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
                                                                at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
                                                                at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
                                                                at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
                                                                at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
                                                                at android.view.View.setFlags(View.java:13277)
                                                                at android.view.View.setVisibility(View.java:9378)
                                                                at com.esafirm.imagepicker.features.ImagePickerActivity.showLoading(ImagePickerActivity.java:465)
                                                                at com.esafirm.imagepicker.features.ImagePickerPresenter.loadImages(ImagePickerPresenter.java:38)
                                                                at com.esafirm.imagepicker.features.ImagePickerActivity.getData(ImagePickerActivity.java:243)
                                                                at com.esafirm.imagepicker.features.ImagePickerActivity.getDataWithPermission(ImagePickerActivity.java:235)
                                                                at com.esafirm.imagepicker.features.ImagePickerActivity.showCapturedImage(ImagePickerActivity.java:442)
                                                                at com.esafirm.imagepicker.features.ImagePickerPresenter.lambda$finishCaptureImage$0(ImagePickerPresenter.java:101)
                                                                at com.esafirm.imagepicker.features.ImagePickerPresenter$$Lambda$1.onImageReady(Unknown Source:4)
                                                                at com.esafirm.imagepicker.features.camera.DefaultCameraModule$1.onScanCompleted(DefaultCameraModule.java:97)
                                                                at android.media.MediaScannerConnection$ClientProxy.onScanCompleted(MediaScannerConnection.java:204)
                                                                at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:53)
                                                                at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:60)
                                                                at android.os.Binder.execTransact(Binder.java:674)

**Comment by esafirm** [comment] 2017-12-12 16:15
@taskfriendinc nice. This is really helpful. Will check on it tomorrow! 👍

**Comment by taskfriendinc** [comment] 2017-12-14 07:23
Any Updates???

**Comment by taskfriendinc** [comment] 2017-12-15 05:38
Hi @esafirm, waiting for your reply.

**Comment by esafirm** [comment] 2017-12-15 07:52
@taskfriendinc the stack trace is indicating that a UI is called from non ui thread. But the line number seems different.

Ex: 
`getData()` should be on 234
`showLoading(boolean isLoading) should be on 455`

I think you're not using the latest version or you already adding something there.

**Comment by taskfriendinc** [comment] 2017-12-15 08:37
Hi @esafirm Can you provide me latest version? Have also checked in `https://github.com/esafirm/android-image-picker/releases/tag/1.9.1` version, which you sent in earlier thread.

Looking forward to hearing from you.

**Comment by esafirm** [comment] 2017-12-15 09:25
@taskfriendinc that is the latest version. 

It strange the stack trace didn't point out to the same line of code

https://github.com/esafirm/android-image-picker/blob/master/imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerActivity.java#L455

**Comment by esafirm** [comment] 2017-12-15 09:27
@taskfriendinc i guess i will check on it again tonight.

**Comment by taskfriendinc** [comment] 2017-12-15 10:19
Now copied your ImagePickerActivity into my code, still showing same error.
Now showLoading is located at line number 455.
Please check.

12-15 15:45:25.480 3016-3235/com.example V/ImagePicker: File /storage/emulated/0/1513332910284.jpg was scanned successfully: content://media/external/file/12491
12-15 15:45:25.497 3016-3235/com.example W/Binder: Caught a RuntimeException from the binder stub implementation.
                                                          android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                              at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7286)
                                                              at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:3426)
                                                              at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
                                                              at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
                                                              at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
                                                              at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
                                                              at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
                                                              at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
                                                              at android.view.View.setFlags(View.java:13277)
                                                              at android.view.View.setVisibility(View.java:9378)
                                                              at com.esafirm.imagepicker.features.ImagePickerActivity.showLoading(ImagePickerActivity.java:456)
                                                              at com.esafirm.imagepicker.features.ImagePickerPresenter.loadImages(ImagePickerPresenter.java:38)
                                                              at com.esafirm.imagepicker.features.ImagePickerActivity.getData(ImagePickerActivity.java:236)
                                                              at com.esafirm.imagepicker.features.ImagePickerActivity.getDataWithPermission(ImagePickerActivity.java:228)
                                                              at com.esafirm.imagepicker.features.ImagePickerActivity.showCapturedImage(ImagePickerActivity.java:433)
                                                              at com.esafirm.imagepicker.features.ImagePickerPresenter.lambda$finishCaptureImage$0(ImagePickerPresenter.java:101)
                                                              at com.esafirm.imagepicker.features.ImagePickerPresenter$$Lambda$1.onImageReady(Unknown Source:4)
                                                              at com.esafirm.imagepicker.features.camera.DefaultCameraModule$1.onScanCompleted(DefaultCameraModule.java:97)
                                                              at android.media.MediaScannerConnection$ClientProxy.onScanCompleted(MediaScannerConnection.java:204)
                                                              at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:53)
                                                              at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:60)
                                                              at android.os.Binder.execTransact(Binder.java:674)
12-15 15:45:30.422 3016-3057/com.example V/FA: Inactivity, disconnecting from the service

**Comment by esafirm** [comment] 2017-12-15 13:22
@taskfriendinc i think i know the problem is. 
```
getView().showLoading(true);
```

Called in worker thread. Still don't know why it's not crashing in my emulator thought. It should have.

Will fix it ASAP

**Comment by esafirm** [comment] 2017-12-15 13:47
@taskfriendinc please try this https://github.com/esafirm/android-image-picker/releases/tag/1.9.2

**Comment by esafirm** [comment] 2017-12-19 06:12
@taskfriendinc any update mate?

**Comment by taskfriendinc** [comment] 2017-12-19 09:11
Hi @esafirm,

Have observed one thing.
Content type of pixel device(which one is having issue) is different than content type of other devices/emulator.

/storage/emulated/0/IMG_20171219_1410384989786822633130980.jpg was scanned successfully: **content://media/external/images/media/142** :  {Captured in emulator having OS Oreo}

/storage/emulated/0/IMG_20171219_1419311272976850886480137.jpg was scanned successfully: **content://media/external/file/12595** :  {Captured in pixel phone having OS Oreo}

/storage/emulated/0/IMG_20171219_140644-1143445963.jpg was scanned successfully: **content://media/external/images/media/967** :  {Captured in samsung phone having OS Marshmellow}

Is this cause of issue? Please suggest.

**Comment by esafirm** [comment] 2017-12-20 07:07
@taskfriendinc does `1.9.2` fix your issue? 
From your stack trace, the problem is definitely a thread problem.

The problem is that `getView.showLoading()` is called on the worker thread ( in this case a binder thread)

The `Uri` should not be a problem because we're using the file path. This is why we're using media scanner.

**Comment by taskfriendinc** [comment] 2017-12-20 09:48
Hi @esafirm,
No, 1.9.2 not fixed my issue.
As you said problem is getView.showLoading() is called on the worker thread ( in this case a binder thread) then, what is the solution for it? Any idea?
Am checking in latest code i.e. 1.9.2

**Comment by esafirm** [comment] 2017-12-20 23:16
This line here 
https://github.com/esafirm/android-image-picker/commit/300c3dd522dc7f6e87062b86effd3494beb33fc6#diff-4dc2de67251fee7fb4b73ebd0e9b1e53R38

**Comment by taskfriendinc** [comment] 2017-12-21 09:21
Hi @esafirm 
That work's for me. I just followed your above steps. Added lines as you shown. :+1: 
I appreciate your coordination, which helped me lots. :)
Thank you very much :)

**Comment by esafirm** [comment] 2017-12-23 17:48
You're welcome 👍

**Closed by esafirm** 2017-12-23 17:48 UTC
