### ISSUE TITLE
Please help me check permission create file for Android 10

### ISSUE THREAD

**Issue by longquangpham90** [esafirm/android-image-picker#388] opened 2021-10-07 01:42 UTC
## Expected Behavior
Grant Permission and open Only Camera

## Actual Behavior
Grant permission CAMERA, error when create file  
```
kotlin.io.NoSuchFileException: /storage/emulated/0/Android/data/com.musiconline.app/files/Pictures/Camera/IMG_20211002_191137_439.jpg: The source file doesn't exist.
   kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
   kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
```
## Specifications

  - Image Picker Version: v2.4.7
  - Android OS: v10
  - Phone: Mi8

**Comment by esafirm** [comment] 2022-11-19 22:53
Duplicate of https://github.com/esafirm/android-image-picker/issues/393

**Closed by esafirm** 2022-11-19 22:53 UTC
