### ISSUE TITLE
Image take from ImagePickerActivity is not updated in gallery

### ISSUE THREAD

**Issue by hak-tpl** [esafirm/android-image-picker#64] opened 2017-07-20 12:43 UTC
Image taken from camera icon in image picker activity is not update in gallery. It appears after re launch of the ImagePickerActivity

**Comment by esafirm** [comment] 2017-07-30 04:30
Does the image appear after some time?

**Comment by hak-tpl** [comment] 2017-07-31 04:46
When I take the image from camera the no. of folders in the activity gets duplicated twice. However the image still don't appear in Camera folder. Appearance of take n image can only be observed on relaunch of ImagePickerActivity.

**Comment by esafirm** [comment] 2017-07-31 06:52
@hak-tpl as for the duplicated folder, it's already fixed in `1.7.5` 
But i can't reproduce your other issue

**Comment by hak-tpl** [comment] 2017-07-31 07:19
I was using 1.7.4. All my issues are fixed in 1.7.5.

Thanks

**Comment by esafirm** [comment] 2017-09-02 05:43
@hak-tpl glad i could help 😄

**Closed** 2017-09-02 05:43 UTC

**Comment by HammadNasir** [comment] 2017-10-01 14:24
@esafirm I'm facing the same issue in 1.7.5 as well as 1.8.0

What to do?

**Comment by esafirm** [comment] 2017-10-01 16:38
@HammadNasir strange, this should be fixed in 1.8.0
please use the latest version `1.9.0` after that if it's still happen i will check again.

**Comment by HammadNasir** [comment] 2017-10-02 01:13
I'm getting this error while trying to add `1.9.0` version:

`Error:Failed to resolve: com.android.support:support-annotations:26.0.2`

**Comment by HammadNasir** [comment] 2017-10-05 13:24
@esafirm please reply. What should I do now?

**Comment by esafirm** [comment] 2017-10-05 14:04
@HammadNasir i don't think it was from android-image-picker. It doesn't use support version version 26 yet. 

Maybe your problem is because you haven't add the google repo in your `build.gradle`

```
 maven {
            url 'https://maven.google.com'
        }
```

Please google your problem or browse the code before asking something like this.

**Comment by HammadNasir** [comment] 2017-10-06 05:37
@esafirm thanks for replying. Adding `maven {url 'https://maven.google.com'}` solved that issue but the captured Image is still not appearing in the activity on devices running Lollipop and below. It is working fine for devices running Marshmallow.

Please help with this too.

Thanks!
